// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ad.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MigrateAdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateAdRequest) Reset()         { *m = MigrateAdRequest{} }
func (m *MigrateAdRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateAdRequest) ProtoMessage()    {}
func (*MigrateAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{0}
}

func (m *MigrateAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateAdRequest.Unmarshal(m, b)
}
func (m *MigrateAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateAdRequest.Marshal(b, m, deterministic)
}
func (m *MigrateAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateAdRequest.Merge(m, src)
}
func (m *MigrateAdRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateAdRequest.Size(m)
}
func (m *MigrateAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateAdRequest proto.InternalMessageInfo

type MigrateAdResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateAdResponse) Reset()         { *m = MigrateAdResponse{} }
func (m *MigrateAdResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateAdResponse) ProtoMessage()    {}
func (*MigrateAdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{1}
}

func (m *MigrateAdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateAdResponse.Unmarshal(m, b)
}
func (m *MigrateAdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateAdResponse.Marshal(b, m, deterministic)
}
func (m *MigrateAdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateAdResponse.Merge(m, src)
}
func (m *MigrateAdResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateAdResponse.Size(m)
}
func (m *MigrateAdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateAdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateAdResponse proto.InternalMessageInfo

func (m *MigrateAdResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 增
type AddAdRequest struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Groupid              uint32   `protobuf:"varint,2,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Priority             uint32   `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Display              uint32   `protobuf:"varint,10,opt,name=display,proto3" json:"display,omitempty"`
	State                uint32   `protobuf:"varint,11,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAdRequest) Reset()         { *m = AddAdRequest{} }
func (m *AddAdRequest) String() string { return proto.CompactTextString(m) }
func (*AddAdRequest) ProtoMessage()    {}
func (*AddAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{2}
}

func (m *AddAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAdRequest.Unmarshal(m, b)
}
func (m *AddAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAdRequest.Marshal(b, m, deterministic)
}
func (m *AddAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAdRequest.Merge(m, src)
}
func (m *AddAdRequest) XXX_Size() int {
	return xxx_messageInfo_AddAdRequest.Size(m)
}
func (m *AddAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAdRequest proto.InternalMessageInfo

func (m *AddAdRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AddAdRequest) GetGroupid() uint32 {
	if m != nil {
		return m.Groupid
	}
	return 0
}

func (m *AddAdRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddAdRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddAdRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddAdRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AddAdRequest) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AddAdRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddAdRequest) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AddAdRequest) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func (m *AddAdRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type AddAdResponse struct {
	Adid                 uint32   `protobuf:"varint,1,opt,name=adid,proto3" json:"adid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAdResponse) Reset()         { *m = AddAdResponse{} }
func (m *AddAdResponse) String() string { return proto.CompactTextString(m) }
func (*AddAdResponse) ProtoMessage()    {}
func (*AddAdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{3}
}

func (m *AddAdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAdResponse.Unmarshal(m, b)
}
func (m *AddAdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAdResponse.Marshal(b, m, deterministic)
}
func (m *AddAdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAdResponse.Merge(m, src)
}
func (m *AddAdResponse) XXX_Size() int {
	return xxx_messageInfo_AddAdResponse.Size(m)
}
func (m *AddAdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAdResponse proto.InternalMessageInfo

func (m *AddAdResponse) GetAdid() uint32 {
	if m != nil {
		return m.Adid
	}
	return 0
}

// 删
type DeleteAdRequest struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Groupid              uint32   `protobuf:"varint,2,opt,name=groupid,proto3" json:"groupid,omitempty"`
	AdidList             []uint32 `protobuf:"varint,3,rep,packed,name=adid_list,json=adidList,proto3" json:"adid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdRequest) Reset()         { *m = DeleteAdRequest{} }
func (m *DeleteAdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAdRequest) ProtoMessage()    {}
func (*DeleteAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{4}
}

func (m *DeleteAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdRequest.Unmarshal(m, b)
}
func (m *DeleteAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdRequest.Merge(m, src)
}
func (m *DeleteAdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAdRequest.Size(m)
}
func (m *DeleteAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdRequest proto.InternalMessageInfo

func (m *DeleteAdRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *DeleteAdRequest) GetGroupid() uint32 {
	if m != nil {
		return m.Groupid
	}
	return 0
}

func (m *DeleteAdRequest) GetAdidList() []uint32 {
	if m != nil {
		return m.AdidList
	}
	return nil
}

type DeleteAdResponse struct {
	RowsAffected         uint32   `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAdResponse) Reset()         { *m = DeleteAdResponse{} }
func (m *DeleteAdResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAdResponse) ProtoMessage()    {}
func (*DeleteAdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{5}
}

func (m *DeleteAdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAdResponse.Unmarshal(m, b)
}
func (m *DeleteAdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAdResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdResponse.Merge(m, src)
}
func (m *DeleteAdResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAdResponse.Size(m)
}
func (m *DeleteAdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdResponse proto.InternalMessageInfo

func (m *DeleteAdResponse) GetRowsAffected() uint32 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

// 查
type GetAdListRequest struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Groupid              uint32   `protobuf:"varint,2,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Display              uint32   `protobuf:"varint,7,opt,name=display,proto3" json:"display,omitempty"`
	State                uint32   `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdListRequest) Reset()         { *m = GetAdListRequest{} }
func (m *GetAdListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdListRequest) ProtoMessage()    {}
func (*GetAdListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{6}
}

func (m *GetAdListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdListRequest.Unmarshal(m, b)
}
func (m *GetAdListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdListRequest.Marshal(b, m, deterministic)
}
func (m *GetAdListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdListRequest.Merge(m, src)
}
func (m *GetAdListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdListRequest.Size(m)
}
func (m *GetAdListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdListRequest proto.InternalMessageInfo

func (m *GetAdListRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetAdListRequest) GetGroupid() uint32 {
	if m != nil {
		return m.Groupid
	}
	return 0
}

func (m *GetAdListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAdListRequest) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *GetAdListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAdListRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetAdListRequest) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func (m *GetAdListRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetAdListResponse struct {
	List                 []*AdListElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                uint32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAdListResponse) Reset()         { *m = GetAdListResponse{} }
func (m *GetAdListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAdListResponse) ProtoMessage()    {}
func (*GetAdListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{7}
}

func (m *GetAdListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdListResponse.Unmarshal(m, b)
}
func (m *GetAdListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdListResponse.Marshal(b, m, deterministic)
}
func (m *GetAdListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdListResponse.Merge(m, src)
}
func (m *GetAdListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAdListResponse.Size(m)
}
func (m *GetAdListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdListResponse proto.InternalMessageInfo

func (m *GetAdListResponse) GetList() []*AdListElement {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetAdListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AdListElement struct {
	Adid                 uint32   `protobuf:"varint,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Url                  string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Priority             uint32   `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Display              uint32   `protobuf:"varint,9,opt,name=display,proto3" json:"display,omitempty"`
	CreateAt             string   `protobuf:"bytes,10,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdListElement) Reset()         { *m = AdListElement{} }
func (m *AdListElement) String() string { return proto.CompactTextString(m) }
func (*AdListElement) ProtoMessage()    {}
func (*AdListElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{8}
}

func (m *AdListElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdListElement.Unmarshal(m, b)
}
func (m *AdListElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdListElement.Marshal(b, m, deterministic)
}
func (m *AdListElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdListElement.Merge(m, src)
}
func (m *AdListElement) XXX_Size() int {
	return xxx_messageInfo_AdListElement.Size(m)
}
func (m *AdListElement) XXX_DiscardUnknown() {
	xxx_messageInfo_AdListElement.DiscardUnknown(m)
}

var xxx_messageInfo_AdListElement proto.InternalMessageInfo

func (m *AdListElement) GetAdid() uint32 {
	if m != nil {
		return m.Adid
	}
	return 0
}

func (m *AdListElement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdListElement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdListElement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AdListElement) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdListElement) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AdListElement) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AdListElement) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AdListElement) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func (m *AdListElement) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

// 改
type EditAdRequest struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Groupid              uint32   `protobuf:"varint,2,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Adid                 uint32   `protobuf:"varint,3,opt,name=adid,proto3" json:"adid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,8,opt,name=cover,proto3" json:"cover,omitempty"`
	Url                  string   `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Priority             uint32   `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Display              uint32   `protobuf:"varint,11,opt,name=display,proto3" json:"display,omitempty"`
	State                uint32   `protobuf:"varint,12,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditAdRequest) Reset()         { *m = EditAdRequest{} }
func (m *EditAdRequest) String() string { return proto.CompactTextString(m) }
func (*EditAdRequest) ProtoMessage()    {}
func (*EditAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{9}
}

func (m *EditAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditAdRequest.Unmarshal(m, b)
}
func (m *EditAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditAdRequest.Marshal(b, m, deterministic)
}
func (m *EditAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditAdRequest.Merge(m, src)
}
func (m *EditAdRequest) XXX_Size() int {
	return xxx_messageInfo_EditAdRequest.Size(m)
}
func (m *EditAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditAdRequest proto.InternalMessageInfo

func (m *EditAdRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *EditAdRequest) GetGroupid() uint32 {
	if m != nil {
		return m.Groupid
	}
	return 0
}

func (m *EditAdRequest) GetAdid() uint32 {
	if m != nil {
		return m.Adid
	}
	return 0
}

func (m *EditAdRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditAdRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditAdRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditAdRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *EditAdRequest) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *EditAdRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EditAdRequest) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *EditAdRequest) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func (m *EditAdRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type EditAdResponse struct {
	RowsAffected         uint32   `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditAdResponse) Reset()         { *m = EditAdResponse{} }
func (m *EditAdResponse) String() string { return proto.CompactTextString(m) }
func (*EditAdResponse) ProtoMessage()    {}
func (*EditAdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{10}
}

func (m *EditAdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditAdResponse.Unmarshal(m, b)
}
func (m *EditAdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditAdResponse.Marshal(b, m, deterministic)
}
func (m *EditAdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditAdResponse.Merge(m, src)
}
func (m *EditAdResponse) XXX_Size() int {
	return xxx_messageInfo_EditAdResponse.Size(m)
}
func (m *EditAdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditAdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditAdResponse proto.InternalMessageInfo

func (m *EditAdResponse) GetRowsAffected() uint32 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

// 获取广告投放列表
type GetAdPlacementListRequest struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Groupid              uint32   `protobuf:"varint,2,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdPlacementListRequest) Reset()         { *m = GetAdPlacementListRequest{} }
func (m *GetAdPlacementListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdPlacementListRequest) ProtoMessage()    {}
func (*GetAdPlacementListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{11}
}

func (m *GetAdPlacementListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdPlacementListRequest.Unmarshal(m, b)
}
func (m *GetAdPlacementListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdPlacementListRequest.Marshal(b, m, deterministic)
}
func (m *GetAdPlacementListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdPlacementListRequest.Merge(m, src)
}
func (m *GetAdPlacementListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdPlacementListRequest.Size(m)
}
func (m *GetAdPlacementListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdPlacementListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdPlacementListRequest proto.InternalMessageInfo

func (m *GetAdPlacementListRequest) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetAdPlacementListRequest) GetGroupid() uint32 {
	if m != nil {
		return m.Groupid
	}
	return 0
}

func (m *GetAdPlacementListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAdPlacementListRequest) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type GetAdPlacementListResponse struct {
	List                 []*AdPlacementListElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                uint32                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetAdPlacementListResponse) Reset()         { *m = GetAdPlacementListResponse{} }
func (m *GetAdPlacementListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAdPlacementListResponse) ProtoMessage()    {}
func (*GetAdPlacementListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{12}
}

func (m *GetAdPlacementListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdPlacementListResponse.Unmarshal(m, b)
}
func (m *GetAdPlacementListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdPlacementListResponse.Marshal(b, m, deterministic)
}
func (m *GetAdPlacementListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdPlacementListResponse.Merge(m, src)
}
func (m *GetAdPlacementListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAdPlacementListResponse.Size(m)
}
func (m *GetAdPlacementListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdPlacementListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdPlacementListResponse proto.InternalMessageInfo

func (m *GetAdPlacementListResponse) GetList() []*AdPlacementListElement {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetAdPlacementListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AdPlacementListElement struct {
	Adid                 uint32   `protobuf:"varint,1,opt,name=adid,proto3" json:"adid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	Url                  string   `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Priority             uint32   `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Display              uint32   `protobuf:"varint,9,opt,name=display,proto3" json:"display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdPlacementListElement) Reset()         { *m = AdPlacementListElement{} }
func (m *AdPlacementListElement) String() string { return proto.CompactTextString(m) }
func (*AdPlacementListElement) ProtoMessage()    {}
func (*AdPlacementListElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fe9fe9dbc34d4ab, []int{13}
}

func (m *AdPlacementListElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdPlacementListElement.Unmarshal(m, b)
}
func (m *AdPlacementListElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdPlacementListElement.Marshal(b, m, deterministic)
}
func (m *AdPlacementListElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdPlacementListElement.Merge(m, src)
}
func (m *AdPlacementListElement) XXX_Size() int {
	return xxx_messageInfo_AdPlacementListElement.Size(m)
}
func (m *AdPlacementListElement) XXX_DiscardUnknown() {
	xxx_messageInfo_AdPlacementListElement.DiscardUnknown(m)
}

var xxx_messageInfo_AdPlacementListElement proto.InternalMessageInfo

func (m *AdPlacementListElement) GetAdid() uint32 {
	if m != nil {
		return m.Adid
	}
	return 0
}

func (m *AdPlacementListElement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdPlacementListElement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdPlacementListElement) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AdPlacementListElement) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdPlacementListElement) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AdPlacementListElement) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AdPlacementListElement) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AdPlacementListElement) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func init() {
	proto.RegisterType((*MigrateAdRequest)(nil), "proto.MigrateAdRequest")
	proto.RegisterType((*MigrateAdResponse)(nil), "proto.MigrateAdResponse")
	proto.RegisterType((*AddAdRequest)(nil), "proto.AddAdRequest")
	proto.RegisterType((*AddAdResponse)(nil), "proto.AddAdResponse")
	proto.RegisterType((*DeleteAdRequest)(nil), "proto.DeleteAdRequest")
	proto.RegisterType((*DeleteAdResponse)(nil), "proto.DeleteAdResponse")
	proto.RegisterType((*GetAdListRequest)(nil), "proto.GetAdListRequest")
	proto.RegisterType((*GetAdListResponse)(nil), "proto.GetAdListResponse")
	proto.RegisterType((*AdListElement)(nil), "proto.AdListElement")
	proto.RegisterType((*EditAdRequest)(nil), "proto.EditAdRequest")
	proto.RegisterType((*EditAdResponse)(nil), "proto.EditAdResponse")
	proto.RegisterType((*GetAdPlacementListRequest)(nil), "proto.GetAdPlacementListRequest")
	proto.RegisterType((*GetAdPlacementListResponse)(nil), "proto.GetAdPlacementListResponse")
	proto.RegisterType((*AdPlacementListElement)(nil), "proto.AdPlacementListElement")
}

func init() { proto.RegisterFile("ad.proto", fileDescriptor_8fe9fe9dbc34d4ab) }

var fileDescriptor_8fe9fe9dbc34d4ab = []byte{
	// 790 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0x41, 0x6f, 0xda, 0x48,
	0x14, 0x16, 0xd8, 0x80, 0xfd, 0x08, 0x09, 0x4c, 0x58, 0x62, 0x9c, 0xac, 0x44, 0x9c, 0x0b, 0x5a,
	0x69, 0x83, 0x92, 0xd5, 0x6a, 0xa5, 0xbd, 0x21, 0x6d, 0xb4, 0x97, 0x46, 0x4a, 0xe9, 0xa1, 0x6a,
	0x0f, 0x45, 0x53, 0x3c, 0x41, 0x56, 0x0d, 0x76, 0xed, 0x49, 0xaa, 0x54, 0x3d, 0xe5, 0x2f, 0x54,
	0xea, 0x9f, 0xe8, 0xb5, 0xff, 0xa2, 0xc7, 0xfe, 0x85, 0x9e, 0xfb, 0x1b, 0xaa, 0x79, 0x33, 0x76,
	0x06, 0x30, 0xa8, 0x51, 0xa4, 0x1e, 0x7a, 0x62, 0xde, 0x9b, 0xc7, 0x37, 0xef, 0x7d, 0xef, 0x7b,
	0x7e, 0x60, 0x51, 0xff, 0x38, 0x4e, 0x22, 0x1e, 0x91, 0x0a, 0xfe, 0xb8, 0x07, 0xd3, 0x28, 0x9a,
	0x86, 0x6c, 0x40, 0xe3, 0x60, 0x40, 0xe7, 0xf3, 0x88, 0x53, 0x1e, 0x44, 0xf3, 0x54, 0x06, 0x79,
	0x04, 0x9a, 0xe7, 0xc1, 0x34, 0xa1, 0x9c, 0x0d, 0xfd, 0x11, 0x7b, 0x7d, 0xc5, 0x52, 0xee, 0xfd,
	0x09, 0x2d, 0xcd, 0x97, 0xc6, 0xd1, 0x3c, 0x65, 0xc4, 0x81, 0xda, 0x8c, 0xa5, 0x29, 0x9d, 0x32,
	0xa7, 0xd4, 0x2b, 0xf5, 0xed, 0x51, 0x66, 0x7a, 0x1f, 0xca, 0xb0, 0x35, 0xf4, 0xfd, 0xfc, 0xff,
	0xa4, 0x0d, 0x15, 0x1a, 0xc7, 0x81, 0xaf, 0x02, 0xa5, 0x21, 0x00, 0xa6, 0x49, 0x74, 0x25, 0xfc,
	0xe5, 0x5e, 0xa9, 0xdf, 0x18, 0x65, 0x26, 0x21, 0x60, 0xce, 0xe9, 0x8c, 0x39, 0x06, 0x86, 0xe3,
	0x59, 0x60, 0xf0, 0x80, 0x87, 0xcc, 0x31, 0x25, 0x06, 0x1a, 0xa4, 0x07, 0x75, 0x9f, 0xa5, 0x93,
	0x24, 0x88, 0x45, 0x0d, 0x4e, 0x05, 0xef, 0x74, 0x17, 0xe9, 0x40, 0x35, 0x61, 0x33, 0x9a, 0xbc,
	0x72, 0xaa, 0x78, 0xa9, 0x2c, 0x81, 0x37, 0x89, 0xae, 0x59, 0xe2, 0xd4, 0x24, 0x1e, 0x1a, 0xa4,
	0x09, 0xc6, 0x55, 0x12, 0x3a, 0x16, 0xfa, 0xc4, 0x91, 0xb8, 0x60, 0xc5, 0x49, 0x10, 0x25, 0x01,
	0xbf, 0x71, 0x6c, 0x4c, 0x33, 0xb7, 0x45, 0x05, 0x7e, 0x90, 0xc6, 0x21, 0xbd, 0x71, 0x40, 0x56,
	0xa0, 0x4c, 0x81, 0x9e, 0x72, 0xca, 0x99, 0x53, 0x47, 0xbf, 0x34, 0xbc, 0x23, 0x68, 0x28, 0x5e,
	0x14, 0x87, 0x04, 0x4c, 0xea, 0x2b, 0x5e, 0x1a, 0x23, 0x3c, 0x7b, 0x2f, 0x60, 0xe7, 0x3f, 0x16,
	0x32, 0x8d, 0xff, 0x7b, 0xf3, 0xb7, 0x0f, 0xb6, 0x80, 0x1a, 0x87, 0x41, 0xca, 0x1d, 0xa3, 0x67,
	0x88, 0xa4, 0x85, 0xe3, 0x51, 0x90, 0x72, 0xef, 0x1f, 0x68, 0xde, 0xe1, 0xab, 0x3c, 0x8e, 0xa0,
	0x91, 0x44, 0x6f, 0xd2, 0x31, 0xbd, 0xbc, 0x64, 0x13, 0xce, 0xb2, 0x84, 0xb6, 0x84, 0x73, 0xa8,
	0x7c, 0xde, 0xe7, 0x12, 0x34, 0xff, 0x67, 0x7c, 0x88, 0x30, 0x0f, 0x68, 0x6d, 0x2c, 0x24, 0x63,
	0xc8, 0x8a, 0xc5, 0x99, 0x74, 0xc1, 0x8a, 0x59, 0x32, 0x46, 0xbf, 0x29, 0xc3, 0x63, 0x96, 0x5c,
	0x88, 0xab, 0x4c, 0x09, 0x95, 0x22, 0x25, 0x54, 0x75, 0x25, 0x68, 0xbd, 0xa8, 0xad, 0xe9, 0x85,
	0xa5, 0xf7, 0xe2, 0x09, 0xb4, 0xb4, 0x62, 0x14, 0x0f, 0x7d, 0x30, 0x91, 0xb3, 0x52, 0xcf, 0xe8,
	0xd7, 0x4f, 0xdb, 0x72, 0x24, 0x8e, 0x65, 0xd0, 0x59, 0xc8, 0x66, 0x6c, 0xce, 0x47, 0x18, 0x81,
	0x49, 0x44, 0x9c, 0x86, 0xaa, 0x3e, 0x69, 0x78, 0xb7, 0x65, 0xd1, 0x61, 0x2d, 0xba, 0xa8, 0xc3,
	0x79, 0x51, 0xe5, 0xa2, 0xa2, 0x8c, 0x0d, 0xf2, 0x36, 0x37, 0xc9, 0xbb, 0x52, 0x2c, 0xef, 0x6a,
	0x81, 0xbc, 0x6b, 0xc5, 0xf2, 0xb6, 0xd6, 0xcb, 0xdb, 0x5e, 0xa4, 0x74, 0x1f, 0xec, 0x49, 0xc2,
	0x28, 0x67, 0x63, 0xca, 0x51, 0xfa, 0xf6, 0xc8, 0x92, 0x8e, 0x21, 0xf7, 0x3e, 0x96, 0xa1, 0x71,
	0xe6, 0x07, 0xfc, 0x41, 0xf3, 0x8f, 0xa4, 0x19, 0x05, 0xa4, 0x99, 0x45, 0xa4, 0x55, 0x36, 0x90,
	0x56, 0xdd, 0x44, 0x5a, 0xad, 0x98, 0x34, 0xab, 0x80, 0x34, 0xbb, 0x98, 0x34, 0x58, 0x4f, 0x5a,
	0x7d, 0x8d, 0x0e, 0xb7, 0x74, 0x1d, 0xfe, 0x0d, 0xdb, 0x19, 0x59, 0xf7, 0x19, 0xc6, 0xb7, 0xd0,
	0x45, 0xf9, 0x5e, 0x84, 0x74, 0x82, 0x4a, 0xfb, 0x79, 0x43, 0xe9, 0x31, 0x70, 0x8b, 0xde, 0x56,
	0xe9, 0x9f, 0x2c, 0xcc, 0xd0, 0xef, 0xf9, 0x0c, 0x2d, 0x44, 0xff, 0xc8, 0x30, 0x7d, 0x2b, 0x41,
	0xa7, 0xf8, 0x6f, 0xbf, 0xe6, 0x54, 0x9d, 0x7e, 0x32, 0xa1, 0x3c, 0xf4, 0xc9, 0x73, 0xb0, 0xf3,
	0x6d, 0x4b, 0xf6, 0x14, 0x7f, 0xcb, 0x3b, 0xd9, 0x75, 0x56, 0x2f, 0x64, 0x03, 0x3c, 0xf7, 0xf6,
	0xcb, 0xd7, 0xf7, 0xe5, 0x36, 0x21, 0xb8, 0xe1, 0xaf, 0x4f, 0x06, 0xd4, 0x1f, 0xcc, 0x64, 0x14,
	0x39, 0x87, 0x0a, 0x6e, 0x20, 0xb2, 0x9b, 0xf7, 0xe5, 0x6e, 0x4f, 0xbb, 0xed, 0x45, 0xa7, 0xc2,
	0xeb, 0x22, 0xde, 0xae, 0xb7, 0xad, 0xe1, 0x51, 0xdf, 0xff, 0xb7, 0xf4, 0x07, 0x79, 0x06, 0x56,
	0xb6, 0x4b, 0x48, 0x47, 0xfd, 0x79, 0x69, 0x79, 0xb9, 0x7b, 0x2b, 0x7e, 0x85, 0x7b, 0x80, 0xb8,
	0x1d, 0xaf, 0xa5, 0xe1, 0xfa, 0x18, 0x24, 0xa0, 0x9f, 0x82, 0x9d, 0x7f, 0x9f, 0x73, 0x16, 0x96,
	0xd7, 0x4f, 0xce, 0xc2, 0xca, 0xa7, 0xdc, 0xdb, 0x43, 0xf4, 0x16, 0xd9, 0xd1, 0xd0, 0x51, 0x6c,
	0x8f, 0xa1, 0x2a, 0x07, 0x8e, 0x64, 0xe5, 0x2e, 0x7c, 0xac, 0xdc, 0xdf, 0x96, 0xbc, 0x8b, 0xac,
	0x7a, 0x3a, 0x1e, 0xf3, 0x03, 0x2e, 0x72, 0x7d, 0x07, 0x64, 0x75, 0x20, 0x48, 0x4f, 0xcf, 0xad,
	0x68, 0x4e, 0xdd, 0xc3, 0x0d, 0x11, 0xea, 0xd9, 0x43, 0x7c, 0x76, 0x9f, 0x74, 0xb5, 0x67, 0xe3,
	0x2c, 0x12, 0x17, 0xfc, 0xcb, 0x2a, 0x82, 0xfc, 0xf5, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x02, 0xa5,
	0x67, 0xad, 0xe9, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdClient is the client API for Ad service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdClient interface {
	MigrateAd(ctx context.Context, in *MigrateAdRequest, opts ...grpc.CallOption) (*MigrateAdResponse, error)
	AddAd(ctx context.Context, in *AddAdRequest, opts ...grpc.CallOption) (*AddAdResponse, error)
	DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*DeleteAdResponse, error)
	GetAdList(ctx context.Context, in *GetAdListRequest, opts ...grpc.CallOption) (*GetAdListResponse, error)
	EditAd(ctx context.Context, in *EditAdRequest, opts ...grpc.CallOption) (*EditAdResponse, error)
	GetAdPlacementList(ctx context.Context, in *GetAdPlacementListRequest, opts ...grpc.CallOption) (*GetAdPlacementListResponse, error)
}

type adClient struct {
	cc *grpc.ClientConn
}

func NewAdClient(cc *grpc.ClientConn) AdClient {
	return &adClient{cc}
}

func (c *adClient) MigrateAd(ctx context.Context, in *MigrateAdRequest, opts ...grpc.CallOption) (*MigrateAdResponse, error) {
	out := new(MigrateAdResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/MigrateAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) AddAd(ctx context.Context, in *AddAdRequest, opts ...grpc.CallOption) (*AddAdResponse, error) {
	out := new(AddAdResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/AddAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*DeleteAdResponse, error) {
	out := new(DeleteAdResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/DeleteAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) GetAdList(ctx context.Context, in *GetAdListRequest, opts ...grpc.CallOption) (*GetAdListResponse, error) {
	out := new(GetAdListResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/GetAdList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) EditAd(ctx context.Context, in *EditAdRequest, opts ...grpc.CallOption) (*EditAdResponse, error) {
	out := new(EditAdResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/EditAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adClient) GetAdPlacementList(ctx context.Context, in *GetAdPlacementListRequest, opts ...grpc.CallOption) (*GetAdPlacementListResponse, error) {
	out := new(GetAdPlacementListResponse)
	err := c.cc.Invoke(ctx, "/proto.Ad/GetAdPlacementList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdServer is the server API for Ad service.
type AdServer interface {
	MigrateAd(context.Context, *MigrateAdRequest) (*MigrateAdResponse, error)
	AddAd(context.Context, *AddAdRequest) (*AddAdResponse, error)
	DeleteAd(context.Context, *DeleteAdRequest) (*DeleteAdResponse, error)
	GetAdList(context.Context, *GetAdListRequest) (*GetAdListResponse, error)
	EditAd(context.Context, *EditAdRequest) (*EditAdResponse, error)
	GetAdPlacementList(context.Context, *GetAdPlacementListRequest) (*GetAdPlacementListResponse, error)
}

// UnimplementedAdServer can be embedded to have forward compatible implementations.
type UnimplementedAdServer struct {
}

func (*UnimplementedAdServer) MigrateAd(ctx context.Context, req *MigrateAdRequest) (*MigrateAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateAd not implemented")
}
func (*UnimplementedAdServer) AddAd(ctx context.Context, req *AddAdRequest) (*AddAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAd not implemented")
}
func (*UnimplementedAdServer) DeleteAd(ctx context.Context, req *DeleteAdRequest) (*DeleteAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAd not implemented")
}
func (*UnimplementedAdServer) GetAdList(ctx context.Context, req *GetAdListRequest) (*GetAdListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdList not implemented")
}
func (*UnimplementedAdServer) EditAd(ctx context.Context, req *EditAdRequest) (*EditAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditAd not implemented")
}
func (*UnimplementedAdServer) GetAdPlacementList(ctx context.Context, req *GetAdPlacementListRequest) (*GetAdPlacementListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdPlacementList not implemented")
}

func RegisterAdServer(s *grpc.Server, srv AdServer) {
	s.RegisterService(&_Ad_serviceDesc, srv)
}

func _Ad_MigrateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).MigrateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/MigrateAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).MigrateAd(ctx, req.(*MigrateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_AddAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).AddAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/AddAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).AddAd(ctx, req.(*AddAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_DeleteAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).DeleteAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/DeleteAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).DeleteAd(ctx, req.(*DeleteAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_GetAdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).GetAdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/GetAdList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).GetAdList(ctx, req.(*GetAdListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_EditAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).EditAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/EditAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).EditAd(ctx, req.(*EditAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ad_GetAdPlacementList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdPlacementListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServer).GetAdPlacementList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ad/GetAdPlacementList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServer).GetAdPlacementList(ctx, req.(*GetAdPlacementListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ad_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ad",
	HandlerType: (*AdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateAd",
			Handler:    _Ad_MigrateAd_Handler,
		},
		{
			MethodName: "AddAd",
			Handler:    _Ad_AddAd_Handler,
		},
		{
			MethodName: "DeleteAd",
			Handler:    _Ad_DeleteAd_Handler,
		},
		{
			MethodName: "GetAdList",
			Handler:    _Ad_GetAdList_Handler,
		},
		{
			MethodName: "EditAd",
			Handler:    _Ad_EditAd_Handler,
		},
		{
			MethodName: "GetAdPlacementList",
			Handler:    _Ad_GetAdPlacementList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ad.proto",
}
