// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// command
type RowsAffectedResponse struct {
	RowsAffected         uint32   `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowsAffectedResponse) Reset()         { *m = RowsAffectedResponse{} }
func (m *RowsAffectedResponse) String() string { return proto.CompactTextString(m) }
func (*RowsAffectedResponse) ProtoMessage()    {}
func (*RowsAffectedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *RowsAffectedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowsAffectedResponse.Unmarshal(m, b)
}
func (m *RowsAffectedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowsAffectedResponse.Marshal(b, m, deterministic)
}
func (m *RowsAffectedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowsAffectedResponse.Merge(m, src)
}
func (m *RowsAffectedResponse) XXX_Size() int {
	return xxx_messageInfo_RowsAffectedResponse.Size(m)
}
func (m *RowsAffectedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RowsAffectedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RowsAffectedResponse proto.InternalMessageInfo

func (m *RowsAffectedResponse) GetRowsAffected() uint32 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

// 迁移
type MigrateArticleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateArticleRequest) Reset()         { *m = MigrateArticleRequest{} }
func (m *MigrateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateArticleRequest) ProtoMessage()    {}
func (*MigrateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{1}
}

func (m *MigrateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateArticleRequest.Unmarshal(m, b)
}
func (m *MigrateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateArticleRequest.Marshal(b, m, deterministic)
}
func (m *MigrateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateArticleRequest.Merge(m, src)
}
func (m *MigrateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateArticleRequest.Size(m)
}
func (m *MigrateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateArticleRequest proto.InternalMessageInfo

type MigrateArticleResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateArticleResponse) Reset()         { *m = MigrateArticleResponse{} }
func (m *MigrateArticleResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateArticleResponse) ProtoMessage()    {}
func (*MigrateArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{2}
}

func (m *MigrateArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateArticleResponse.Unmarshal(m, b)
}
func (m *MigrateArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateArticleResponse.Marshal(b, m, deterministic)
}
func (m *MigrateArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateArticleResponse.Merge(m, src)
}
func (m *MigrateArticleResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateArticleResponse.Size(m)
}
func (m *MigrateArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateArticleResponse proto.InternalMessageInfo

func (m *MigrateArticleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 增
type AddArticleRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TopicId              uint32   `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Source               string   `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Recommendation       uint32   `protobuf:"varint,8,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Content              string   `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	State                uint32   `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddArticleRequest) Reset()         { *m = AddArticleRequest{} }
func (m *AddArticleRequest) String() string { return proto.CompactTextString(m) }
func (*AddArticleRequest) ProtoMessage()    {}
func (*AddArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{3}
}

func (m *AddArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleRequest.Unmarshal(m, b)
}
func (m *AddArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleRequest.Marshal(b, m, deterministic)
}
func (m *AddArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleRequest.Merge(m, src)
}
func (m *AddArticleRequest) XXX_Size() int {
	return xxx_messageInfo_AddArticleRequest.Size(m)
}
func (m *AddArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleRequest proto.InternalMessageInfo

func (m *AddArticleRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddArticleRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AddArticleRequest) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *AddArticleRequest) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AddArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddArticleRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AddArticleRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *AddArticleRequest) GetRecommendation() uint32 {
	if m != nil {
		return m.Recommendation
	}
	return 0
}

func (m *AddArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AddArticleRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type AddArticleResponse struct {
	ArticleId            uint32   `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddArticleResponse) Reset()         { *m = AddArticleResponse{} }
func (m *AddArticleResponse) String() string { return proto.CompactTextString(m) }
func (*AddArticleResponse) ProtoMessage()    {}
func (*AddArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{4}
}

func (m *AddArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleResponse.Unmarshal(m, b)
}
func (m *AddArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleResponse.Marshal(b, m, deterministic)
}
func (m *AddArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleResponse.Merge(m, src)
}
func (m *AddArticleResponse) XXX_Size() int {
	return xxx_messageInfo_AddArticleResponse.Size(m)
}
func (m *AddArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleResponse proto.InternalMessageInfo

func (m *AddArticleResponse) GetArticleId() uint32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

// 删
type DeleteArticleRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ArticleIdList        []uint32 `protobuf:"varint,3,rep,packed,name=article_id_list,json=articleIdList,proto3" json:"article_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArticleRequest) Reset()         { *m = DeleteArticleRequest{} }
func (m *DeleteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArticleRequest) ProtoMessage()    {}
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{5}
}

func (m *DeleteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArticleRequest.Unmarshal(m, b)
}
func (m *DeleteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArticleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArticleRequest.Merge(m, src)
}
func (m *DeleteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArticleRequest.Size(m)
}
func (m *DeleteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArticleRequest proto.InternalMessageInfo

func (m *DeleteArticleRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeleteArticleRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *DeleteArticleRequest) GetArticleIdList() []uint32 {
	if m != nil {
		return m.ArticleIdList
	}
	return nil
}

// 查
type GetArticleListRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TopicId              uint32   `protobuf:"varint,5,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Source               string   `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	State                uint32   `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{6}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetArticleListRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetArticleListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticleListRequest) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *GetArticleListRequest) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *GetArticleListRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetArticleListRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetArticleListRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetArticleListResponse struct {
	List                 []*ArticleListElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                uint32                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetArticleListResponse) Reset()         { *m = GetArticleListResponse{} }
func (m *GetArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleListResponse) ProtoMessage()    {}
func (*GetArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{7}
}

func (m *GetArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListResponse.Unmarshal(m, b)
}
func (m *GetArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListResponse.Merge(m, src)
}
func (m *GetArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleListResponse.Size(m)
}
func (m *GetArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListResponse proto.InternalMessageInfo

func (m *GetArticleListResponse) GetList() []*ArticleListElement {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetArticleListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ArticleListElement struct {
	ArticleId            uint32   `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	TopicId              uint32   `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Cover                string   `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Source               string   `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Recommendation       uint32   `protobuf:"varint,7,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	State                uint32   `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	ReleasedAt           string   `protobuf:"bytes,9,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	CreateAt             string   `protobuf:"bytes,10,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleListElement) Reset()         { *m = ArticleListElement{} }
func (m *ArticleListElement) String() string { return proto.CompactTextString(m) }
func (*ArticleListElement) ProtoMessage()    {}
func (*ArticleListElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{8}
}

func (m *ArticleListElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleListElement.Unmarshal(m, b)
}
func (m *ArticleListElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleListElement.Marshal(b, m, deterministic)
}
func (m *ArticleListElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleListElement.Merge(m, src)
}
func (m *ArticleListElement) XXX_Size() int {
	return xxx_messageInfo_ArticleListElement.Size(m)
}
func (m *ArticleListElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleListElement.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleListElement proto.InternalMessageInfo

func (m *ArticleListElement) GetArticleId() uint32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *ArticleListElement) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *ArticleListElement) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ArticleListElement) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleListElement) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ArticleListElement) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ArticleListElement) GetRecommendation() uint32 {
	if m != nil {
		return m.Recommendation
	}
	return 0
}

func (m *ArticleListElement) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ArticleListElement) GetReleasedAt() string {
	if m != nil {
		return m.ReleasedAt
	}
	return ""
}

func (m *ArticleListElement) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

// 改
type EditArticleRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ArticleId            uint32   `protobuf:"varint,3,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	TopicId              uint32   `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Cover                string   `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Source               string   `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Recommendation       uint32   `protobuf:"varint,9,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Content              string   `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	State                uint32   `protobuf:"varint,11,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditArticleRequest) Reset()         { *m = EditArticleRequest{} }
func (m *EditArticleRequest) String() string { return proto.CompactTextString(m) }
func (*EditArticleRequest) ProtoMessage()    {}
func (*EditArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{9}
}

func (m *EditArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditArticleRequest.Unmarshal(m, b)
}
func (m *EditArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditArticleRequest.Marshal(b, m, deterministic)
}
func (m *EditArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditArticleRequest.Merge(m, src)
}
func (m *EditArticleRequest) XXX_Size() int {
	return xxx_messageInfo_EditArticleRequest.Size(m)
}
func (m *EditArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditArticleRequest proto.InternalMessageInfo

func (m *EditArticleRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *EditArticleRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *EditArticleRequest) GetArticleId() uint32 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *EditArticleRequest) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *EditArticleRequest) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *EditArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditArticleRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *EditArticleRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *EditArticleRequest) GetRecommendation() uint32 {
	if m != nil {
		return m.Recommendation
	}
	return 0
}

func (m *EditArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *EditArticleRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

// 专题
// 迁移
type MigrateArticleTopicRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateArticleTopicRequest) Reset()         { *m = MigrateArticleTopicRequest{} }
func (m *MigrateArticleTopicRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateArticleTopicRequest) ProtoMessage()    {}
func (*MigrateArticleTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{10}
}

func (m *MigrateArticleTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateArticleTopicRequest.Unmarshal(m, b)
}
func (m *MigrateArticleTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateArticleTopicRequest.Marshal(b, m, deterministic)
}
func (m *MigrateArticleTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateArticleTopicRequest.Merge(m, src)
}
func (m *MigrateArticleTopicRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateArticleTopicRequest.Size(m)
}
func (m *MigrateArticleTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateArticleTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateArticleTopicRequest proto.InternalMessageInfo

type MigrateArticleTopicResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateArticleTopicResponse) Reset()         { *m = MigrateArticleTopicResponse{} }
func (m *MigrateArticleTopicResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateArticleTopicResponse) ProtoMessage()    {}
func (*MigrateArticleTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{11}
}

func (m *MigrateArticleTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateArticleTopicResponse.Unmarshal(m, b)
}
func (m *MigrateArticleTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateArticleTopicResponse.Marshal(b, m, deterministic)
}
func (m *MigrateArticleTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateArticleTopicResponse.Merge(m, src)
}
func (m *MigrateArticleTopicResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateArticleTopicResponse.Size(m)
}
func (m *MigrateArticleTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateArticleTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateArticleTopicResponse proto.InternalMessageInfo

func (m *MigrateArticleTopicResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 查
type GetArticleTopicListRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	State                uint32   `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleTopicListRequest) Reset()         { *m = GetArticleTopicListRequest{} }
func (m *GetArticleTopicListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleTopicListRequest) ProtoMessage()    {}
func (*GetArticleTopicListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{12}
}

func (m *GetArticleTopicListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleTopicListRequest.Unmarshal(m, b)
}
func (m *GetArticleTopicListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleTopicListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleTopicListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleTopicListRequest.Merge(m, src)
}
func (m *GetArticleTopicListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleTopicListRequest.Size(m)
}
func (m *GetArticleTopicListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleTopicListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleTopicListRequest proto.InternalMessageInfo

func (m *GetArticleTopicListRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetArticleTopicListRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetArticleTopicListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticleTopicListRequest) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *GetArticleTopicListRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type GetArticleTopicListResponse struct {
	List                 []*ArticleTopicListElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                uint32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetArticleTopicListResponse) Reset()         { *m = GetArticleTopicListResponse{} }
func (m *GetArticleTopicListResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleTopicListResponse) ProtoMessage()    {}
func (*GetArticleTopicListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{13}
}

func (m *GetArticleTopicListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleTopicListResponse.Unmarshal(m, b)
}
func (m *GetArticleTopicListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleTopicListResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleTopicListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleTopicListResponse.Merge(m, src)
}
func (m *GetArticleTopicListResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleTopicListResponse.Size(m)
}
func (m *GetArticleTopicListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleTopicListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleTopicListResponse proto.InternalMessageInfo

func (m *GetArticleTopicListResponse) GetList() []*ArticleTopicListElement {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetArticleTopicListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ArticleTopicListElement struct {
	TopicId              uint32   `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort                 uint32   `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	State                uint32   `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	CreateAt             string   `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleTopicListElement) Reset()         { *m = ArticleTopicListElement{} }
func (m *ArticleTopicListElement) String() string { return proto.CompactTextString(m) }
func (*ArticleTopicListElement) ProtoMessage()    {}
func (*ArticleTopicListElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{14}
}

func (m *ArticleTopicListElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleTopicListElement.Unmarshal(m, b)
}
func (m *ArticleTopicListElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleTopicListElement.Marshal(b, m, deterministic)
}
func (m *ArticleTopicListElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleTopicListElement.Merge(m, src)
}
func (m *ArticleTopicListElement) XXX_Size() int {
	return xxx_messageInfo_ArticleTopicListElement.Size(m)
}
func (m *ArticleTopicListElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleTopicListElement.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleTopicListElement proto.InternalMessageInfo

func (m *ArticleTopicListElement) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *ArticleTopicListElement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArticleTopicListElement) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ArticleTopicListElement) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ArticleTopicListElement) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

// 增
type AddArticleTopicRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GroupId              uint32   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sort                 uint32   `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	State                uint32   `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddArticleTopicRequest) Reset()         { *m = AddArticleTopicRequest{} }
func (m *AddArticleTopicRequest) String() string { return proto.CompactTextString(m) }
func (*AddArticleTopicRequest) ProtoMessage()    {}
func (*AddArticleTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{15}
}

func (m *AddArticleTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleTopicRequest.Unmarshal(m, b)
}
func (m *AddArticleTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleTopicRequest.Marshal(b, m, deterministic)
}
func (m *AddArticleTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleTopicRequest.Merge(m, src)
}
func (m *AddArticleTopicRequest) XXX_Size() int {
	return xxx_messageInfo_AddArticleTopicRequest.Size(m)
}
func (m *AddArticleTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleTopicRequest proto.InternalMessageInfo

func (m *AddArticleTopicRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AddArticleTopicRequest) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AddArticleTopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddArticleTopicRequest) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AddArticleTopicRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type AddArticleTopicResponse struct {
	TopicId              uint32   `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddArticleTopicResponse) Reset()         { *m = AddArticleTopicResponse{} }
func (m *AddArticleTopicResponse) String() string { return proto.CompactTextString(m) }
func (*AddArticleTopicResponse) ProtoMessage()    {}
func (*AddArticleTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{16}
}

func (m *AddArticleTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleTopicResponse.Unmarshal(m, b)
}
func (m *AddArticleTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleTopicResponse.Marshal(b, m, deterministic)
}
func (m *AddArticleTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleTopicResponse.Merge(m, src)
}
func (m *AddArticleTopicResponse) XXX_Size() int {
	return xxx_messageInfo_AddArticleTopicResponse.Size(m)
}
func (m *AddArticleTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleTopicResponse proto.InternalMessageInfo

func (m *AddArticleTopicResponse) GetTopicId() uint32 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func init() {
	proto.RegisterType((*RowsAffectedResponse)(nil), "proto.RowsAffectedResponse")
	proto.RegisterType((*MigrateArticleRequest)(nil), "proto.MigrateArticleRequest")
	proto.RegisterType((*MigrateArticleResponse)(nil), "proto.MigrateArticleResponse")
	proto.RegisterType((*AddArticleRequest)(nil), "proto.AddArticleRequest")
	proto.RegisterType((*AddArticleResponse)(nil), "proto.AddArticleResponse")
	proto.RegisterType((*DeleteArticleRequest)(nil), "proto.DeleteArticleRequest")
	proto.RegisterType((*GetArticleListRequest)(nil), "proto.GetArticleListRequest")
	proto.RegisterType((*GetArticleListResponse)(nil), "proto.GetArticleListResponse")
	proto.RegisterType((*ArticleListElement)(nil), "proto.ArticleListElement")
	proto.RegisterType((*EditArticleRequest)(nil), "proto.EditArticleRequest")
	proto.RegisterType((*MigrateArticleTopicRequest)(nil), "proto.MigrateArticleTopicRequest")
	proto.RegisterType((*MigrateArticleTopicResponse)(nil), "proto.MigrateArticleTopicResponse")
	proto.RegisterType((*GetArticleTopicListRequest)(nil), "proto.GetArticleTopicListRequest")
	proto.RegisterType((*GetArticleTopicListResponse)(nil), "proto.GetArticleTopicListResponse")
	proto.RegisterType((*ArticleTopicListElement)(nil), "proto.ArticleTopicListElement")
	proto.RegisterType((*AddArticleTopicRequest)(nil), "proto.AddArticleTopicRequest")
	proto.RegisterType((*AddArticleTopicResponse)(nil), "proto.AddArticleTopicResponse")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0x67, 0xec, 0xf9, 0xa9, 0x30, 0x59, 0xd1, 0x49, 0x26, 0x9e, 0x9f, 0x64, 0xb3, 0x0d,
	0x5a, 0x45, 0x48, 0x6c, 0x44, 0x16, 0x09, 0x09, 0x4e, 0x23, 0xb1, 0x42, 0x91, 0x40, 0x42, 0x16,
	0x57, 0x34, 0x6a, 0xec, 0xce, 0x60, 0xe1, 0x71, 0x7b, 0xed, 0x4e, 0xf6, 0x8a, 0x38, 0x20, 0x6e,
	0x1c, 0x96, 0x67, 0xc8, 0x13, 0xf0, 0x26, 0x1c, 0x78, 0x01, 0x1e, 0x04, 0xb9, 0xba, 0xed, 0xb1,
	0x3d, 0xed, 0x19, 0x14, 0xa4, 0x3d, 0xcd, 0x74, 0x55, 0x77, 0x7f, 0x55, 0x5f, 0x7d, 0x55, 0x6d,
	0x18, 0xb1, 0x54, 0x86, 0x7e, 0xc4, 0x5f, 0x24, 0xa9, 0x90, 0x82, 0x38, 0xf8, 0x33, 0x9d, 0xaf,
	0x84, 0x58, 0x45, 0xfc, 0x8a, 0x25, 0xe1, 0x15, 0x8b, 0x63, 0x21, 0x99, 0x0c, 0x45, 0x9c, 0xa9,
	0x4d, 0xf4, 0x0b, 0x38, 0xf6, 0xc4, 0x9b, 0x6c, 0x71, 0x7b, 0xcb, 0x7d, 0xc9, 0x03, 0x8f, 0x67,
	0x89, 0x88, 0x33, 0x4e, 0x3e, 0x80, 0x51, 0x2a, 0xde, 0x64, 0x4b, 0xa6, 0x1d, 0xae, 0x75, 0x61,
	0x5d, 0x8e, 0xbc, 0xf7, 0xd2, 0xca, 0x66, 0x7a, 0x0a, 0x27, 0xdf, 0x84, 0xab, 0x94, 0x49, 0xbe,
	0x50, 0xc8, 0x1e, 0x7f, 0x7d, 0xc7, 0x33, 0x49, 0xaf, 0x61, 0xdc, 0x74, 0xe8, 0x7b, 0x5d, 0xe8,
	0xaf, 0x79, 0x96, 0xb1, 0x15, 0xc7, 0x1b, 0x87, 0x5e, 0xb1, 0xa4, 0x7f, 0x74, 0xe0, 0xfd, 0x45,
	0x10, 0xd4, 0x6f, 0x22, 0x27, 0xd0, 0x63, 0x49, 0xb2, 0x0c, 0x03, 0xbd, 0xdd, 0x61, 0x49, 0x72,
	0x13, 0x90, 0x09, 0x0c, 0x56, 0xa9, 0xb8, 0x43, 0x47, 0x07, 0x23, 0xeb, 0xe3, 0x5a, 0xb9, 0xa4,
	0x48, 0x42, 0x3f, 0x77, 0x75, 0x95, 0x0b, 0xd7, 0x37, 0x01, 0x39, 0x06, 0xc7, 0x17, 0xf7, 0x3c,
	0x75, 0x6d, 0x75, 0x17, 0x2e, 0x72, 0xab, 0x0c, 0x65, 0xc4, 0x5d, 0x47, 0x59, 0x71, 0x41, 0xc6,
	0xd0, 0x63, 0x77, 0xf2, 0x47, 0x91, 0xba, 0x3d, 0x34, 0xeb, 0x55, 0x6e, 0xcf, 0xc4, 0x5d, 0xea,
	0x73, 0xb7, 0xaf, 0xec, 0x6a, 0x45, 0x9e, 0xc3, 0x61, 0xca, 0x7d, 0xb1, 0x5e, 0xf3, 0x38, 0x40,
	0x86, 0xdd, 0x01, 0x82, 0x37, 0xac, 0x39, 0x01, 0xbe, 0x88, 0x25, 0x8f, 0xa5, 0x3b, 0x54, 0x04,
	0xe8, 0x65, 0x1e, 0x47, 0x26, 0x99, 0xe4, 0x2e, 0xe0, 0x41, 0xb5, 0xa0, 0x2f, 0x81, 0x54, 0x59,
	0xd1, 0x34, 0x9e, 0x01, 0xe8, 0x62, 0x17, 0xd4, 0x8c, 0xbc, 0xa1, 0xb6, 0xdc, 0x04, 0x34, 0x81,
	0xe3, 0x2f, 0x79, 0xc4, 0x9b, 0x75, 0x79, 0x04, 0x9b, 0xcf, 0xe1, 0xc9, 0x06, 0x68, 0x19, 0x85,
	0x99, 0x74, 0xbb, 0x17, 0xdd, 0xcb, 0x91, 0x37, 0x2a, 0xd1, 0xbe, 0x0e, 0x33, 0x49, 0xff, 0xb6,
	0xe0, 0xe4, 0x2b, 0x2e, 0x35, 0x5e, 0x6e, 0x7a, 0x3c, 0x26, 0x01, 0x3b, 0xc9, 0x05, 0xa2, 0xaa,
	0x87, 0xff, 0xf3, 0xed, 0x09, 0x4f, 0x97, 0x68, 0xb7, 0xd5, 0xf6, 0x84, 0xa7, 0xdf, 0x6a, 0x57,
	0x59, 0x70, 0x67, 0xab, 0xe0, 0xaa, 0xb4, 0xbd, 0x46, 0x69, 0x8d, 0x25, 0x2c, 0x0b, 0x30, 0xa8,
	0x16, 0xe0, 0x7b, 0x18, 0x37, 0x13, 0xd3, 0x45, 0xf8, 0x18, 0x6c, 0x24, 0xc4, 0xba, 0xe8, 0x5e,
	0x1e, 0x5c, 0x4f, 0x54, 0x47, 0xbd, 0xa8, 0xec, 0x7c, 0x15, 0xf1, 0x35, 0x8f, 0xa5, 0x87, 0xdb,
	0x30, 0x18, 0x21, 0x59, 0xa4, 0xd3, 0x55, 0x0b, 0xfa, 0xd0, 0x01, 0xb2, 0x7d, 0x64, 0x4f, 0x81,
	0x6b, 0x39, 0x77, 0x5a, 0x44, 0xde, 0x35, 0x8a, 0xdc, 0x36, 0x8b, 0xdc, 0x69, 0x11, 0x79, 0x6f,
	0x8f, 0xc8, 0xfb, 0x46, 0x91, 0x1b, 0x99, 0x24, 0x4f, 0xe1, 0x20, 0xe5, 0x11, 0x67, 0x19, 0x0f,
	0x96, 0xac, 0x90, 0x3f, 0x14, 0xa6, 0x85, 0x24, 0x33, 0x18, 0xfa, 0x29, 0x67, 0x92, 0xe7, 0x6e,
	0x40, 0xf7, 0x40, 0x19, 0x16, 0x92, 0xfe, 0xd9, 0x01, 0xf2, 0x2a, 0x08, 0xe5, 0xff, 0x96, 0x74,
	0x9d, 0xda, 0xee, 0x2e, 0x6a, 0xed, 0x16, 0x6a, 0x1d, 0x23, 0xb5, 0x3d, 0x33, 0xb5, 0xfd, 0x16,
	0x6a, 0x07, 0x7b, 0xa8, 0x1d, 0xee, 0x9b, 0x1f, 0xd0, 0x32, 0x3f, 0x0e, 0xaa, 0xf2, 0x9d, 0xc3,
	0xb4, 0x3e, 0x8a, 0xbf, 0xcb, 0x93, 0x29, 0x06, 0xf5, 0x67, 0x30, 0x33, 0x7a, 0xf7, 0x4e, 0xeb,
	0xb7, 0x16, 0x4c, 0x37, 0x6d, 0x81, 0xa7, 0xde, 0x69, 0xd3, 0x97, 0xc9, 0x3a, 0xd5, 0x64, 0x57,
	0x30, 0x33, 0x06, 0xa5, 0xd3, 0xb9, 0xae, 0x35, 0xec, 0x79, 0xbd, 0x61, 0xcb, 0xed, 0xff, 0xa5,
	0x6b, 0x7f, 0xb7, 0xe0, 0xb4, 0xe5, 0x5c, 0x4d, 0x40, 0x56, 0x5d, 0x40, 0x04, 0xec, 0x98, 0xad,
	0x39, 0xde, 0x35, 0xf4, 0xf0, 0x7f, 0x6e, 0xcb, 0x44, 0x2a, 0x8b, 0xc4, 0xf3, 0xff, 0x9b, 0xec,
	0xec, 0x6a, 0xff, 0xd4, 0xda, 0xc3, 0x69, 0xb4, 0xc7, 0x6f, 0x16, 0x8c, 0x37, 0x0f, 0x45, 0xb5,
	0xc8, 0x8f, 0x2b, 0x06, 0xc6, 0xd9, 0x35, 0xc4, 0x69, 0x9b, 0xe2, 0xac, 0x55, 0xe1, 0x53, 0x38,
	0xdd, 0x8a, 0x44, 0x57, 0xa0, 0x9d, 0x9b, 0xeb, 0x87, 0x3e, 0xf4, 0xf5, 0x19, 0xf2, 0x1a, 0x0e,
	0xeb, 0xb2, 0x24, 0x73, 0x5d, 0x2c, 0xe3, 0xf7, 0xc6, 0xf4, 0xac, 0xc5, 0xab, 0x50, 0x29, 0xfd,
	0xe5, 0xaf, 0x7f, 0xde, 0x76, 0xe6, 0xf4, 0x14, 0x3f, 0x82, 0xee, 0x3f, 0xb9, 0xd2, 0xdd, 0x7e,
	0xb5, 0x56, 0xfb, 0x3f, 0xb7, 0x3e, 0x22, 0x0c, 0x60, 0x13, 0x34, 0x71, 0x0b, 0x6d, 0x34, 0x3f,
	0x48, 0xa6, 0x13, 0x83, 0x47, 0xc3, 0x9c, 0x23, 0x8c, 0x4b, 0x8f, 0x9a, 0x30, 0x2c, 0x08, 0x72,
	0x88, 0x08, 0x46, 0xb5, 0x57, 0x99, 0xcc, 0xf4, 0x5d, 0xa6, 0xb7, 0x7a, 0x5a, 0x38, 0x4d, 0x9f,
	0x67, 0xf4, 0x19, 0x42, 0xcd, 0xe8, 0xb8, 0x09, 0x15, 0xe0, 0x55, 0x39, 0xda, 0x4f, 0x70, 0x58,
	0x7f, 0xb7, 0x4a, 0x0e, 0x8d, 0xef, 0x74, 0xc9, 0xa1, 0xf9, 0xb1, 0xa3, 0x73, 0x44, 0x1c, 0x93,
	0xe3, 0x26, 0x22, 0x76, 0xc9, 0x2d, 0x1c, 0x54, 0x66, 0x33, 0x29, 0x48, 0xda, 0x9e, 0xd7, 0xbb,
	0xd3, 0x7a, 0x8a, 0x20, 0x13, 0xba, 0x05, 0xc2, 0x83, 0x50, 0xe6, 0x49, 0xfd, 0x6a, 0xc1, 0x91,
	0x61, 0x60, 0x91, 0x67, 0x46, 0x01, 0x54, 0xbb, 0x60, 0x4a, 0x77, 0x6d, 0xd1, 0xf8, 0x97, 0x88,
	0x4f, 0xe9, 0x59, 0x13, 0x1f, 0x45, 0x5a, 0x95, 0xcb, 0x3d, 0x3c, 0x69, 0x68, 0x9c, 0x9c, 0x6d,
	0x29, 0xa3, 0x86, 0x7f, 0xde, 0xe6, 0xd6, 0xd8, 0x1f, 0x22, 0xf6, 0x39, 0x9d, 0x98, 0xb1, 0xb5,
	0x86, 0x7e, 0xb6, 0xe0, 0xc8, 0x30, 0xe2, 0x4a, 0x02, 0xda, 0x67, 0x72, 0x49, 0xc0, 0x8e, 0x09,
	0x59, 0x74, 0x0a, 0x99, 0x9a, 0x83, 0xc8, 0x6b, 0xfd, 0x43, 0x0f, 0xaf, 0x79, 0xf9, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcd, 0x36, 0x28, 0xc9, 0x6f, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	// 文章
	MigrateArticle(ctx context.Context, in *MigrateArticleRequest, opts ...grpc.CallOption) (*MigrateArticleResponse, error)
	AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*AddArticleResponse, error)
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*RowsAffectedResponse, error)
	GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error)
	EditArticle(ctx context.Context, in *EditArticleRequest, opts ...grpc.CallOption) (*RowsAffectedResponse, error)
	// 专题
	MigrateArticleTopic(ctx context.Context, in *MigrateArticleTopicRequest, opts ...grpc.CallOption) (*MigrateArticleTopicResponse, error)
	AddArticleTopic(ctx context.Context, in *AddArticleTopicRequest, opts ...grpc.CallOption) (*AddArticleTopicResponse, error)
	GetArticleTopicList(ctx context.Context, in *GetArticleTopicListRequest, opts ...grpc.CallOption) (*GetArticleTopicListResponse, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) MigrateArticle(ctx context.Context, in *MigrateArticleRequest, opts ...grpc.CallOption) (*MigrateArticleResponse, error) {
	out := new(MigrateArticleResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/MigrateArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*AddArticleResponse, error) {
	out := new(AddArticleResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/AddArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*RowsAffectedResponse, error) {
	out := new(RowsAffectedResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/DeleteArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error) {
	out := new(GetArticleListResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/GetArticleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) EditArticle(ctx context.Context, in *EditArticleRequest, opts ...grpc.CallOption) (*RowsAffectedResponse, error) {
	out := new(RowsAffectedResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/EditArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) MigrateArticleTopic(ctx context.Context, in *MigrateArticleTopicRequest, opts ...grpc.CallOption) (*MigrateArticleTopicResponse, error) {
	out := new(MigrateArticleTopicResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/MigrateArticleTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) AddArticleTopic(ctx context.Context, in *AddArticleTopicRequest, opts ...grpc.CallOption) (*AddArticleTopicResponse, error) {
	out := new(AddArticleTopicResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/AddArticleTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticleTopicList(ctx context.Context, in *GetArticleTopicListRequest, opts ...grpc.CallOption) (*GetArticleTopicListResponse, error) {
	out := new(GetArticleTopicListResponse)
	err := c.cc.Invoke(ctx, "/proto.Article/GetArticleTopicList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	// 文章
	MigrateArticle(context.Context, *MigrateArticleRequest) (*MigrateArticleResponse, error)
	AddArticle(context.Context, *AddArticleRequest) (*AddArticleResponse, error)
	DeleteArticle(context.Context, *DeleteArticleRequest) (*RowsAffectedResponse, error)
	GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error)
	EditArticle(context.Context, *EditArticleRequest) (*RowsAffectedResponse, error)
	// 专题
	MigrateArticleTopic(context.Context, *MigrateArticleTopicRequest) (*MigrateArticleTopicResponse, error)
	AddArticleTopic(context.Context, *AddArticleTopicRequest) (*AddArticleTopicResponse, error)
	GetArticleTopicList(context.Context, *GetArticleTopicListRequest) (*GetArticleTopicListResponse, error)
}

// UnimplementedArticleServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServer struct {
}

func (*UnimplementedArticleServer) MigrateArticle(ctx context.Context, req *MigrateArticleRequest) (*MigrateArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateArticle not implemented")
}
func (*UnimplementedArticleServer) AddArticle(ctx context.Context, req *AddArticleRequest) (*AddArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArticle not implemented")
}
func (*UnimplementedArticleServer) DeleteArticle(ctx context.Context, req *DeleteArticleRequest) (*RowsAffectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (*UnimplementedArticleServer) GetArticleList(ctx context.Context, req *GetArticleListRequest) (*GetArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleList not implemented")
}
func (*UnimplementedArticleServer) EditArticle(ctx context.Context, req *EditArticleRequest) (*RowsAffectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditArticle not implemented")
}
func (*UnimplementedArticleServer) MigrateArticleTopic(ctx context.Context, req *MigrateArticleTopicRequest) (*MigrateArticleTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateArticleTopic not implemented")
}
func (*UnimplementedArticleServer) AddArticleTopic(ctx context.Context, req *AddArticleTopicRequest) (*AddArticleTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArticleTopic not implemented")
}
func (*UnimplementedArticleServer) GetArticleTopicList(ctx context.Context, req *GetArticleTopicListRequest) (*GetArticleTopicListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleTopicList not implemented")
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_MigrateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).MigrateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/MigrateArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).MigrateArticle(ctx, req.(*MigrateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_AddArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).AddArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/AddArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).AddArticle(ctx, req.(*AddArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/DeleteArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleList(ctx, req.(*GetArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_EditArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).EditArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/EditArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).EditArticle(ctx, req.(*EditArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_MigrateArticleTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateArticleTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).MigrateArticleTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/MigrateArticleTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).MigrateArticleTopic(ctx, req.(*MigrateArticleTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_AddArticleTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).AddArticleTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/AddArticleTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).AddArticleTopic(ctx, req.(*AddArticleTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticleTopicList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleTopicListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleTopicList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Article/GetArticleTopicList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleTopicList(ctx, req.(*GetArticleTopicListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateArticle",
			Handler:    _Article_MigrateArticle_Handler,
		},
		{
			MethodName: "AddArticle",
			Handler:    _Article_AddArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _Article_DeleteArticle_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _Article_GetArticleList_Handler,
		},
		{
			MethodName: "EditArticle",
			Handler:    _Article_EditArticle_Handler,
		},
		{
			MethodName: "MigrateArticleTopic",
			Handler:    _Article_MigrateArticleTopic_Handler,
		},
		{
			MethodName: "AddArticleTopic",
			Handler:    _Article_AddArticleTopic_Handler,
		},
		{
			MethodName: "GetArticleTopicList",
			Handler:    _Article_GetArticleTopicList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
