// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiResponse_Data int32

const (
	ApiResponse_HelloWorldResponse ApiResponse_Data = 0
	ApiResponse_Tmp                ApiResponse_Data = 1
)

var ApiResponse_Data_name = map[int32]string{
	0: "HelloWorldResponse",
	1: "Tmp",
}

var ApiResponse_Data_value = map[string]int32{
	"HelloWorldResponse": 0,
	"Tmp":                1,
}

func (x ApiResponse_Data) String() string {
	return proto.EnumName(ApiResponse_Data_name, int32(x))
}

func (ApiResponse_Data) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1, 0}
}

type HelloWorldRequest struct {
	Referer              string   `protobuf:"bytes,1,opt,name=referer,proto3" json:"referer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

type ApiResponse struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 ApiResponse_Data `protobuf:"varint,3,opt,name=data,proto3,enum=proto.ApiResponse_Data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ApiResponse) Reset()         { *m = ApiResponse{} }
func (m *ApiResponse) String() string { return proto.CompactTextString(m) }
func (*ApiResponse) ProtoMessage()    {}
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *ApiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiResponse.Unmarshal(m, b)
}
func (m *ApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiResponse.Marshal(b, m, deterministic)
}
func (m *ApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiResponse.Merge(m, src)
}
func (m *ApiResponse) XXX_Size() int {
	return xxx_messageInfo_ApiResponse.Size(m)
}
func (m *ApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApiResponse proto.InternalMessageInfo

func (m *ApiResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApiResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ApiResponse) GetData() ApiResponse_Data {
	if m != nil {
		return m.Data
	}
	return ApiResponse_HelloWorldResponse
}

type HelloWorldResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Tmp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tmp) Reset()         { *m = Tmp{} }
func (m *Tmp) String() string { return proto.CompactTextString(m) }
func (*Tmp) ProtoMessage()    {}
func (*Tmp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *Tmp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tmp.Unmarshal(m, b)
}
func (m *Tmp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tmp.Marshal(b, m, deterministic)
}
func (m *Tmp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tmp.Merge(m, src)
}
func (m *Tmp) XXX_Size() int {
	return xxx_messageInfo_Tmp.Size(m)
}
func (m *Tmp) XXX_DiscardUnknown() {
	xxx_messageInfo_Tmp.DiscardUnknown(m)
}

var xxx_messageInfo_Tmp proto.InternalMessageInfo

func (m *Tmp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.ApiResponse_Data", ApiResponse_Data_name, ApiResponse_Data_value)
	proto.RegisterType((*HelloWorldRequest)(nil), "proto.HelloWorldRequest")
	proto.RegisterType((*ApiResponse)(nil), "proto.ApiResponse")
	proto.RegisterType((*HelloWorldResponse)(nil), "proto.HelloWorldResponse")
	proto.RegisterType((*Tmp)(nil), "proto.Tmp")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x34, 0xb5, 0x38, 0xd5, 0x92, 0xce, 0xc1, 0xc6, 0xe2, 0xa1, 0x2c, 0x82, 0x45,
	0x31, 0x81, 0x7a, 0xf3, 0x26, 0x78, 0xf0, 0x1c, 0x45, 0x8f, 0xb2, 0xba, 0x63, 0x0c, 0x24, 0x99,
	0x98, 0xac, 0x88, 0x57, 0x6f, 0x9e, 0x7d, 0x34, 0x5f, 0xc1, 0x07, 0x91, 0xdd, 0x44, 0x0c, 0xd4,
	0xd3, 0xfe, 0xb3, 0x7c, 0xff, 0xec, 0x3f, 0x3b, 0x30, 0x7e, 0xa2, 0x3c, 0xe7, 0xa8, 0xaa, 0xd9,
	0x30, 0x0e, 0xdd, 0x31, 0xdf, 0x4f, 0x99, 0xd3, 0x9c, 0x62, 0x55, 0x65, 0xb1, 0x2a, 0x4b, 0x36,
	0xca, 0x64, 0x5c, 0x36, 0x2d, 0x24, 0x4f, 0x60, 0x7a, 0x69, 0x3d, 0xb7, 0x5c, 0xe7, 0x3a, 0xa1,
	0xe7, 0x17, 0x6a, 0x0c, 0x86, 0x30, 0xaa, 0xe9, 0x91, 0x6a, 0xaa, 0x43, 0xb1, 0x10, 0xcb, 0xad,
	0xe4, 0xb7, 0x94, 0x1f, 0x02, 0xc6, 0xe7, 0x55, 0x96, 0x50, 0x53, 0x71, 0xd9, 0x10, 0x22, 0xf8,
	0x0f, 0xac, 0xc9, 0x61, 0xc3, 0xc4, 0x69, 0x0c, 0x60, 0x50, 0x34, 0x69, 0xe8, 0x39, 0xa7, 0x95,
	0x78, 0x0c, 0xbe, 0x56, 0x46, 0x85, 0x83, 0x85, 0x58, 0x4e, 0x56, 0xb3, 0xf6, 0xe9, 0xa8, 0xd7,
	0x27, 0xba, 0x50, 0x46, 0x25, 0x0e, 0x92, 0x87, 0xe0, 0xdb, 0x0a, 0x77, 0x01, 0xfb, 0xc9, 0x5a,
	0x30, 0xd8, 0xc0, 0x11, 0x0c, 0xae, 0x8b, 0x2a, 0x10, 0xf2, 0xe0, 0x3f, 0x00, 0x27, 0xe0, 0x65,
	0xba, 0xcb, 0xe3, 0x65, 0x5a, 0xee, 0x39, 0xdc, 0x06, 0x2d, 0x55, 0x41, 0xdd, 0x3c, 0x4e, 0xaf,
	0x34, 0xc0, 0x5f, 0x03, 0xbc, 0x81, 0x9d, 0x2b, 0xf5, 0xd6, 0xbb, 0x08, 0xbb, 0x9c, 0x6b, 0xff,
	0x33, 0xc7, 0xf5, 0x09, 0xe4, 0xec, 0xfd, 0xeb, 0xfb, 0xd3, 0x9b, 0xca, 0xed, 0xd8, 0xed, 0xe0,
	0xee, 0xd5, 0x1a, 0xce, 0xc4, 0xd1, 0xfd, 0xa6, 0x63, 0x4f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0x3f, 0x46, 0xf0, 0x9c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	SayHelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*ApiResponse, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, "/proto.HelloWorld/SayHelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	SayHelloWorld(context.Context, *HelloWorldRequest) (*ApiResponse, error)
}

// UnimplementedHelloWorldServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServer struct {
}

func (*UnimplementedHelloWorldServer) SayHelloWorld(ctx context.Context, req *HelloWorldRequest) (*ApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloWorld not implemented")
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_SayHelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).SayHelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloWorld/SayHelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).SayHelloWorld(ctx, req.(*HelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloWorld",
			Handler:    _HelloWorld_SayHelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
